set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
setw -g mode-keys vi

# Copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Custom scripts
bind-key -r i run-shell "tmux neww ~/.config/nvim/script/ch.sh"
bind-key -r R run-shell "tmux neww ~/.config/nvim/script/project.sh"

# Increase visible length
set -g status-left-length 100
set -g status-right-length 200

# Status bar
set-option -g status-position top
set-option -g default-terminal "screen-256color"
set-option -g status-interval 2

# Colors
set-option -g status-bg "#1d2021"
set-option -g status-fg "#ebdbb2"

# Left side
set -g status-left '#[bg=#313031, fg=#55c5ef]#[bg=#55c5ef, fg=#313031,bold]󰣇 #[bg=#313031, fg=#55c5ef] #S #[bg=#1d2021, fg=#313031]#[default]'

# Window list
set -g status-justify left

setw -g window-status-current-format '#[fg=#ff8787,bold]#[fg=#313031,bg=#ff8787]󰋇 #[fg=#ff8787,bg=#313031] #I: #W #[fg=#313031,bg=#1d2021]█#[default]'

setw -g window-status-format '#[fg=#3d3d3d]█#[fg=#cbcbcb,bg=#3d3d3d]#I: #W #[fg=#3d3d3d,bg=#1d2021]█#[default]'

# # full right system infor
# set -g status-right '#[fg=#fb4934] %d-%m-%y #[fg=#83a598]%H:%M:%S #[fg=#8ec07c]CPU: #(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk "{print 100 - \$1\"%\"}" | xargs) #[fg=#d3869b]Mem: #(free | awk "/Mem:/ {printf \"%.1f%%\", \$3/\$2 * 100}") #[fg=#fe8019]Disk: #(df -h / | awk "NR==2{print \$3\"/\"\$2}") #[fg=#b8bb26]Bat: #(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null || echo N/A)% #[fg=#83a598]Net: #(cat /proc/net/dev | awk \"/eth0|wlan0/ {rx+=\\$2; tx+=\\$10} END {print rx/1024/1024 \\\"MB↓ \\\" tx/1024/1024 \\\"MB↑\\\"}\")'

# Right side system info
set -g status-right '#[fg=#8ec07c]CPU: #(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk "{print 100 - \$1\"%\"}" | xargs) #[fg=#d3869b]Mem: #(awk "/MemTotal/ {t=\$2} /MemAvailable/ {a=\$2} END {printf \"%.1f%%\", (t-a)/t*100}" /proc/meminfo) #[fg=#fe8019]Disk: #(df -h / | awk "NR==2{print \$3\"/\"\$2}")'

# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Reload config
bind r source-file ~/.config/nvim/.tmux.conf \; display-message "Config reloaded!"

# TPM
run '~/.tmux/plugins/tpm/tpm'