return {
	require("plugins.conform"),
	require("plugins.auto-session"),
	require("plugins.mason-lspconfig"),
	require("plugins.lspconfig"),
	require("plugins.flash"), -- We removed keys but kept the plugin
	require("plugins.mason"),
	require("plugins.treesitter"),
	require("plugins.ts-autotag"),
	require("plugins.luasnip"),
	require("plugins.colorizer"),
	require("plugins.nvim-cmp"),
	require("plugins.harpoon"),
	require("plugins.trouble"),
	{ "honza/vim-snippets", lazy = true },
	require("plugins.ultisnips"),
	require("plugins.friendly-snippets"),
	require("plugins.windsurf"),
	{ "debugloop/telescope-undo.nvim" },
	require("plugins.telescope-luasnip"),
	require("plugins.telescope-file-browser"),
	require("plugins.markdown"),
	require("plugins.sourcegraph"),
}
